source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'ZFMRACNetwork' do
   
    #AFN
    pod 'AFNetworking'
 
    #ReactiveCoca 
    pod 'ReactiveObjC', '~> 3.1.0'
   
    #网络提示
    pod 'JDStatusBarNotification', '~> 1.5.6'
   
    #提示
    pod 'MBProgressHUD', '~> 1.1.0' 
 end
